apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
      containers:
      - name: production-container
        image: us-east4-docker.pkg.dev/qwiklabs-gcp-02-ae82f94118a9/my-repository/hello-cloudbuild:3c03fbf
        ports:
        - containerPort: 8080
